name: Auto-run

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Ejecutar cada 1 minutos

jobs:
  run-counter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run contador.py
      run: |
        python3 contador.py
